### PR TITLE
Some changes for better dump

### PR DESCRIPTION
**Pull request by hendralize**
- Use device codename in the worst case
- Use Android version of DTC

### CODE REVIEW

**Comment by hendralize** [comment]
Bump @rokibhasansagar

**Comment by rokibhasansagar** [comment]
Wow!
Thanks for the updates. 🥰 

I too don't exactly know the exact difference in Kernel.org's dtc tree from Android's.
But you found a plus point in Android's build, so I thinks it'll be fine to use that.

_BTW, which platform you used to build the binary?
I used Ubuntu 20.04 for all the binaries that I built in this repository._

**Comment by hendralize** [comment]
Hi, thanks for the respond. I use Ubuntu 18.04, since 20.04 version is bugged in my server provider.

**Comment by rokibhasansagar** [comment]
> Hi, thanks for the respond. I use Ubuntu 18.04, since 20.04 version is bugged in my server provider.

No problem, Bionic is stable enough.
So, I'm gonna merge this. 👍🏼

**Pull request merged**
